name: anomalydet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - ipykernel
  - setuptools
  - ca-certificates
  - libgcc-ng
  - zeromq
  - certifi
  - _openmp_mutex
  - openssl
  - decorator
  - pip
  - libstdcxx-ng
  - libgomp
  - pyzmq
  - ncurses
  - libffi
  - pickleshare
  - sqlite
  - xz
  - prompt_toolkit
  - ptyprocess
  - pexpect
  - readline
  - simplegeneric
  - ipython
  - six
  - pygments
  - zlib
  - wcwidth
  - ipython_genutils
  - ld_impl_linux-64
  - libsodium
  - python_abi
  - python-dateutil
  - entrypoints
  - _libgcc_mutex
  - tornado
  - tk
  - traitlets
  - wheel
  - timm
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-generator==1.10
    - attrs==22.2.0
    - bleach==4.1.0
    - cffi==1.15.1
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - defusedxml==0.7.1
    - gym-notices==0.0.8
    - idna==2.10
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipywidgets==7.7.4
    - jinja2==3.0.3
    - joblib==1.1.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==5.2.0
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.3
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.6
    - notebook==6.4.10
    - numpy==1.19.5
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - prometheus-client==0.16.0
    - pycparser==2.21
    - pyrsistent==0.18.0
    - pytz==2023.2
    - pywavelets==1.1.1
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - send2trash==1.8.0
    - tabulate==0.8.10
    - terminado==0.12.1
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - torchattacks==3.3.0
    - tqdm==4.64.1
    - urllib3==1.26.15
    - webencodings==0.5.1
    - widgetsnbextension==3.6.3
    - zipp==3.6.0
    - gdown==4.7.1